### ISSUE TITLE
OperationCanceledException when modifying JS files

### ISSUE THREAD

**Issue by lukemcgregor** [reactjs/React.NET#105]
I get the following whenever I modify JS files which are being used for SSR.

	<TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical">
		<TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier>
		<Description>Unhandled exception</Description>
		<AppDomain>/LM/W3SVC/7/ROOT-2-130709595736844036</AppDomain>
		<Exception>
			<ExceptionType>System.OperationCanceledException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
			<Message>The operation was canceled.</Message>
			<StackTrace>
				at System.Collections.Concurrent.BlockingCollection`1.TryAddWithNoTimeValidation(T item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
				at JSPool.JsEngineWithOwnThread.RunOnThread(Func`2 method)
				at JSPool.JsEngineWithOwnThread.RunOnThread(Action`1 method)
				at JSPool.JsEngineWithOwnThread.Dispose()
				at JSPool.JsPool.DisposeEngine(IJsEngine engine, Boolean repopulateEngines)
				at JSPool.JsPool.Dispose()
				at React.JavaScriptEngineFactory.OnResetPoolTimer(Object state)
				at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
				at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
				at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
				at System.Threading.TimerQueueTimer.CallCallback()
				at System.Threading.TimerQueueTimer.Fire()
				at System.Threading.TimerQueue.FireNextTimers()
				at System.Threading.TimerQueue.AppDomainTimerCallback()
			</StackTrace>
			<ExceptionString>
				System.OperationCanceledException: The operation was canceled.
				at System.Collections.Concurrent.BlockingCollection`1.TryAddWithNoTimeValidation(T item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
				at JSPool.JsEngineWithOwnThread.RunOnThread(Func`2 method)
				at JSPool.JsEngineWithOwnThread.RunOnThread(Action`1 method)
				at JSPool.JsEngineWithOwnThread.Dispose()
				at JSPool.JsPool.DisposeEngine(IJsEngine engine, Boolean repopulateEngines)
				at JSPool.JsPool.Dispose()
				at React.JavaScriptEngineFactory.OnResetPoolTimer(Object state)
				at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
				at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
				at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
				at System.Threading.TimerQueueTimer.CallCallback()
				at System.Threading.TimerQueueTimer.Fire()
				at System.Threading.TimerQueue.FireNextTimers()
				at System.Threading.TimerQueue.AppDomainTimerCallback()
			</ExceptionString>
		</Exception>
	</TraceRecord>

It used to happen in the 1.3.0 occasionally but in 1.4.0 its much more frequent. When it does happen it crashes IISExpress and requires restarting the app.

This is only an issue when developing, I haven't ever seen anything similar in production. My serverside JS file is quite large (over 1mb) as it contains all of my external references and isn't minified, which may be contributing to the issue.

I think its probably due to the application timing out trying to access the file while the file is locked for write.

**Comment by Daniel15** [comment]
Sounds like an issue with JSPool (the library that handles pooling/reuse of JavaScript engines) so I've moved this to https://github.com/Daniel15/JSPool/issues/6.

In the meantime, you can try turning off pooling and seeing if that helps. To do that, call `. SetReuseJavaScriptEngines(false)` in your `ReactConfig.cs` file. This will make execution slower (as it needs to spin up a new JavaScript engine for every request rather than reusing them) but should avoid this issue.

**Comment by lukemcgregor** [comment]
Yeah that totally seems to fix the issue. Ill just leave it off in dev. 

Thanks for the fast response :)
