### ISSUE TITLE
ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by m1is** [reactjs/React.NET#1309]
I created a ReactJS.NET project using the reactnet-webpack template, then upgraded it from React 16 to the latest v18. However when I try to run the out of the box example I get the following error:

> ReferenceError: TextEncoder is not defined
     at eval (<anonymous>:145:19) -> var textEncoder = new TextEncoder();
     at eval (<anonymous>:7002:5)
     at ./node_modules/react-dom/cjs/react-dom-server.browser.development.js (vendor.6d1c51ef.js:23:1)
     at __webpack_require__ (runtime.36e5d9f0.js:85:30)
     at eval (<anonymous>:6:7)
     at ./node_modules/react-dom/server.browser.js (vendor.6d1c51ef.js:59:1)
     at __webpack_require__ (runtime.36e5d9f0.js:85:30)
     at eval (<anonymous>:6:74)
     at eval (<anonymous>:47:30)
     at ./Content/components/expose-components.js (main.ab0e9b20.js:35:1)
     at __webpack_require__ (runtime.36e5d9f0.js:85:30)
     at checkDeferredModules (runtime.36e5d9f0.js:46:23)
     at webpackJsonpCallback (runtime.36e5d9f0.js:33:19)
     at vendor.6d1c51ef.js:1:53
     at JavaScriptEngineSwitcher.V8.V8JsEngine.InnerExecute(String code, String documentName)
     at JavaScriptEngineSwitcher.Core.JsEngineBase.Execute(String code, String documentName)
     at React.JavaScriptEngineFactory.LoadUserScripts(IJsEngine engine)

How would I go about resolving this?

**Comment by ChristianGilmer** [comment]
try downgrading to react and react-dom 16.12.0

**Comment by LinusCenterstrom** [comment]
change the import of ReactDOMServer to be from either
"react-dom/cjs/react-dom-server-legacy.browser.development" or
"react-dom/cjs/react-dom-server-legacy.browser.production.min.js"
instead of reactdom/server

**Comment by m1is** [comment]
> change the import of ReactDOMServer to be from either "react-dom/cjs/react-dom-server-legacy.browser.development" or "react-dom/cjs/react-dom-server-legacy.browser.production.min.js" instead of reactdom/server

I already abandoned this, just too many issues trying to get it to work with Material UI.

**Comment by sebastian-pierre** [comment]
Above solution with linking to the legacy files does not work for me. It keeps throwing the same error, and / or TextEncoder is not a constructor.

**Comment by dustinsoftware** [comment]
Sorry, don’t know of a fix for this. As others have noted, probably best to
move to another library if you need react 18 support.

Probably need to add a note that the library is in maintenance mode, and
folks should stick with react 16 as long as they are on this library.

**Comment by dineshpannu** [comment]
I added https://github.com/anonyco/FastestSmallestTextEncoderDecoder as a polyfill in my server webpack configuration and that seemed to have fixed it.

**Comment by LorenDorez** [comment]
This is due to change React v18 added. The only work around at this time would be to add a polyfill to your build scripts. I started a discussion about plans i have to bring this project up to better support React v18 but its going to require some major changes. https://github.com/reactjs/React.NET/discussions/1343
