### ISSUE TITLE
Lodash & serverside rendering

### ISSUE THREAD

**Issue by janhalama** [reactjs/React.NET#144]
I have problem to use lodash  v3.9.3 javascript library for server side rendering. When I reference the lodash library I receive this exception:

Error while loading "~/ReactJs/Scripts/dest/serverBundle.js": Script threw an exception: Unable to get property 'prototype' of undefined or null reference
Line: 0
Column:0

Stack trace:
   at React.ReactEnvironment.EnsureUserScriptsLoaded()
   at React.ReactEnvironment.CreateComponent[T](String componentName, T props, String containerId)
   at React.Web.Mvc.HtmlHelperExtensions.React[T](HtmlHelper htmlHelper, String componentName, T props, String htmlTag, String containerId, Boolean clientOnly)
   at ASP._Page_Views_Dashboard_Index_cshtml.Execute() in d:\Projects\jablotool-web\JabloTool.WEB\Views\Dashboard\Index.cshtml:line 7
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.StartPage.RunPage()
   at System.Web.WebPages.StartPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)

I use grund for buiding the javascript dependencies.
Jan

**Comment by janhalama** [comment]
My conclusion is that lodash lib is not ready to be used for serverside rendering.
