### ISSUE TITLE
IOException caused script watcher

### ISSUE THREAD

**Issue by gregbty** [reactjs/React.NET#181]
I am using Gulp in my development workflow to handle the compilation of assets including my React components. I usually prefer to keep the IIS Express server running locally so that when I re-build my server-side code (C#) and/or assets, I do not have to restart it. 

After each build, the local IIS Express crashes due to an IOException. In the previous version of React.NET (1.5.5), the stack trace indicated that the issue was being caused by file system watcher used to monitor the transformed scripts. Now it just displays the following error:

```
An unhandled exception of type 'System.IO.IOException' occurred in mscorlib.dll

Additional information: The process cannot access the file '...\www\js\bundles\server.js' because it is being used by another process.
```

During my compilations, the files that contain the React components are removed first which seems to be causing the error. Any ideas?

Here is my React config, if it helps:

``` csharp
var configuration = new ReactSiteConfiguration();
configuration.SetLoadBabel(false);
configuration.AddScriptWithoutTransform("~/www/js/bundles/server.js");
configuration.AllowMsieEngine = false;
configuration.LoadReact = false;
configuration.SetJsonSerializerSettings(new JsonSerializerSettings
{
    StringEscapeHandling = StringEscapeHandling.EscapeHtml,
    ContractResolver = new CamelCasePropertyNamesContractResolver()
});

ReactSiteConfiguration.Configuration = configuration;
```

**Comment by Daniel15** [comment]
Is there any stack trace for that error message, or do you just see the error message with no stack? It would be awesome if you could somehow find a stack trace for the error.

Try `.SetReuseJavaScriptEngines(false)` on your config and see if that helps. That will make page loads slower (it spins up a brand new JS engine on every page load) but should avoid any file locking issues.

**Comment by gregbty** [comment]
I was able to see the stack trace on a previous version of the library but not with the latest.

I will try that later today. If that does work, is there no way to monitor the files without locking or restarting the engine if an IOException is detected? I would rather have the fast page loads.

**Comment by Daniel15** [comment]
How do you generate the `server.js` file? Are you using Webpack, or just Gulp? Can you provide a small Gulpfile that replicates the issue? I haven't seen any similar issues with Webpack.

**Comment by gregbty** [comment]
I can. Here is the stack trace:

```csharp
The process cannot access the file '...\www\js\bundles\server.js' because it is being used by another process.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at React.FileSystemBase.ReadAsString(String relativePath)
   at React.JavaScriptEngineFactory.LoadUserScripts(IJsEngine engine)
   at React.JavaScriptEngineFactory.InitialiseEngine(IJsEngine engine)
   at JSPool.JsPool.CreateEngine()
   at JSPool.JsPool.PopulateEngines()
   at JSPool.JsPool.Recycle()
   at JSPool.JsPool.&amp;lt;InitializeWatcher&amp;gt;b__10_0(Object sender, EventArgs args)
   at JSPool.FileWatcher.OnTimer(Object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
```

**Comment by Daniel15** [comment]
Thanks for the stack trace!

I wonder if JSPool should avoid recycling the pool of JavaScript engines until none of the watched files are locked. Currently it debounces the recycle to handle the case where there's a few changes to the same file in a short period of time. The delay could be increased ([currently it's 25ms](https://github.com/Daniel15/JSPool/blob/master/src/JSPool/FileWatcher.cs#L34-L37)) which would work around this issue, it's a pretty hacky fix though. You could clone JSPool and build your own version with a larger value for `DEBOUNCE_TIMEOUT` and see if that helps

**Comment by johnkors** [comment]
+1. Also using Gulp to watch/build the scripts for react.net.

**Comment by mva3212** [comment]
+1 Also happening with Webpack getting unhandled IOException crashing w3wp.exe in development.  Disabling pooling in development does resolve the issue for me as well.

**Comment by huan086** [comment]
+1, using Gulp and browserify. Crash for me came later, when I refresh the page. Stack trace below


```
Application: iisexpress.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at <Module>.V8Isolate.Create(StdString*, V8IsolateConstraints*, Boolean, Int32)
   at Microsoft.ClearScript.V8.V8IsolateProxyImpl..ctor(System.String, Microsoft.ClearScript.V8.V8RuntimeConstraints, Boolean, Int32)

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeConstructorInfo.Invoke(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[], System.Threading.StackCrawlMark ByRef)
   at System.Activator.CreateInstance(System.Type, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[])
   at System.Activator.CreateInstance(System.Type, System.Object[])
   at Microsoft.ClearScript.V8.V8Proxy.CreateImpl[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object[])
   at Microsoft.ClearScript.V8.V8IsolateProxy.Create(System.String, Microsoft.ClearScript.V8.V8RuntimeConstraints, Boolean, Int32)
   at Microsoft.ClearScript.V8.V8Runtime..ctor(System.String, Microsoft.ClearScript.V8.V8RuntimeConstraints, Microsoft.ClearScript.V8.V8RuntimeFlags, Int32)
   at Microsoft.ClearScript.V8.V8ScriptEngine..ctor(Microsoft.ClearScript.V8.V8Runtime, System.String, Microsoft.ClearScript.V8.V8RuntimeConstraints, Microsoft.ClearScript.V8.V8ScriptEngineFlags, Int32)
   at JavaScriptEngineSwitcher.V8.V8JsEngine..ctor(JavaScriptEngineSwitcher.V8.Configuration.V8Configuration)
   at React.AssemblyRegistration+<>c.<RegisterSupportedEngines>b__3_0()
   at JSPool.JsPool.CreateEngine()
   at JSPool.JsPool.PopulateEngines()
   at JSPool.JsPool.Recycle()
   at JSPool.JsPool.<InitializeWatcher>b__12_0(System.Object, System.EventArgs)
   at JSPool.FileWatcher.OnTimer(System.Object)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()

```

**Comment by AndreyTsvetkov** [comment]
+1, webpack: 

Application: iisexpress.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   at System.IO.StreamReader..ctor(System.String, System.Text.Encoding, Boolean, Int32, Boolean)
   at System.IO.File.InternalReadAllText(System.String, System.Text.Encoding, Boolean)
   at React.JavaScriptEngineFactory.LoadUserScripts(JavaScriptEngineSwitcher.Core.IJsEngine)
   at React.JavaScriptEngineFactory.InitialiseEngine(JavaScriptEngineSwitcher.Core.IJsEngine)
   at JSPool.JsPool`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CreateEngine()
   at JSPool.JsPool`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].PopulateEngines()
   at JSPool.FileWatcher.OnTimer(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

**Comment by dustinsoftware** [comment]
Fixed here https://github.com/reactjs/React.NET/commit/b93e529c8cd6cb4a34ddf2f6203095d7f3da3d29
