### ISSUE TITLE
MSBuild task fails in .vbproj

### ISSUE THREAD

**Issue by jdefontes** [reactjs/React.NET#25]
Create two identical class library projects, one .csproj, one .vbproj and add the TransformJsx task. The .csproj will build, but the .vbproj will fail with the following:
```
Error	13	The "TransformJsx" task failed unexpectedly.
React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.ICache
   at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.Resolve(Type resolveType)
   at React.TinyIoC.TinyIoCContainer.Resolve[ResolveType]()
   at React.MSBuild.TransformJsx.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()	C:\Users\Jason\Projects\Podtrac\Source\users\jdefontes\scratch\MergedVb2\MergedVb2.vbproj	142	9	MergedVb2
```
VS 2012, .NET 4.5.

**Comment by Daniel15** [comment]
I'm going to close this out since I haven't been able to replicate the issue, and haven't received any other reports of it. Let me know if you still encounter this on the latest ReactJS.NET version!
