### ISSUE TITLE
JSPool error with React.NET

### ISSUE THREAD

**Issue by sgraffite** [reactjs/React.NET#250]
I'm not sure if this is a problem with JSPool or how React.NET is interacting with it or something else.

I also do not know of any specific circumstances that cause this and I haven't been able to recognize a pattern to the timing of when it occurs.

<h1>Short error version</h1>
<pre>
System.TypeLoadException: Method 'EmbedHostObject' in type 'JSPool.JsEngineWithOwnThread' from assembly 'JSPool, Version=0.3.0.0, Culture=neutral, PublicKeyToken=2fc7775f73072640' does not have an implementation.

Generated: Thu, 07 Apr 2016 14:56:25 GMT

React.Exceptions.ReactNotInitialisedException: ReactJS.NET has not been initialised correctly. ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.JavaScriptEngineFactory ---> System.TypeLoadException: Method 'EmbedHostObject' in type 'JSPool.JsEngineWithOwnThread' from assembly 'JSPool, Version=0.3.0.0, Culture=neutral, PublicKeyToken=2fc7775f73072640' does not have an implementation.
   at JSPool.JsPool.<CreateEngineFactory>b__12_0()
   at JSPool.JsPool.CreateEngine()
   at JSPool.JsPool.PopulateEngines()
   at JSPool.JsPool..ctor(JsPoolConfig config)
   at React.JavaScriptEngineFactory.CreatePool()
   at React.JavaScriptEngineFactory..ctor(IEnumerable`1 availableFactories, IReactSiteConfiguration config, IFileSystem fileSystem)
   at lambda_method(Closure , Object[] )
   at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
</pre>

<h1>Lengthy error version</h1>
<pre>
System.TypeLoadException: Method 'EmbedHostObject' in type 'JSPool.JsEngineWithOwnThread' from assembly 'JSPool, Version=0.3.0.0, Culture=neutral, PublicKeyToken=2fc7775f73072640' does not have an implementation.

Generated: Thu, 07 Apr 2016 14:56:25 GMT

React.Exceptions.ReactNotInitialisedException: ReactJS.NET has not been initialised correctly. ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.JavaScriptEngineFactory ---> System.TypeLoadException: Method 'EmbedHostObject' in type 'JSPool.JsEngineWithOwnThread' from assembly 'JSPool, Version=0.3.0.0, Culture=neutral, PublicKeyToken=2fc7775f73072640' does not have an implementation.
   at JSPool.JsPool.<CreateEngineFactory>b__12_0()
   at JSPool.JsPool.CreateEngine()
   at JSPool.JsPool.PopulateEngines()
   at JSPool.JsPool..ctor(JsPoolConfig config)
   at React.JavaScriptEngineFactory.CreatePool()
   at React.JavaScriptEngineFactory..ctor(IEnumerable`1 availableFactories, IReactSiteConfiguration config, IFileSystem fileSystem)
   at lambda_method(Closure , Object[] )
   at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.CustomObjectLifetimeFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.Resolve[ResolveType]()
   at React.Web.Mvc.HtmlHelperExtensions.get_Environment()
   --- End of inner exception stack trace ---
   at React.Web.Mvc.HtmlHelperExtensions.get_Environment()
   at React.Web.Mvc.HtmlHelperExtensions.React[T](HtmlHelper htmlHelper, String componentName, T props, String htmlTag, String containerId, Boolean clientOnly, Boolean serverOnly, String containerClass)
   at ASP._Themes_Default_Shared__HeaderSearch_cshtml.Execute() in D:\wtec.git\Singularity\Code\Singularity.Consumer\Themes\Themes\Default\Shared\_HeaderSearch.cshtml:line 5
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at RazorGenerator.Mvc.PrecompiledMvcView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at ASP._Themes_Default_Shared__Header_cshtml.Execute() in D:\wtec.git\Singularity\Code\Singularity.Consumer\Themes\Themes\Default\Shared\_Header.cshtml:line 2
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at RazorGenerator.Mvc.PrecompiledMvcView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at ASP._Themes_Default_Shared__HtmlBody_cshtml.Execute() in D:\wtec.git\Singularity\Code\Singularity.Consumer\Themes\Themes\Default\Shared\_HtmlBody.cshtml:line 6
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at RazorGenerator.Mvc.PrecompiledMvcView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at ASP._Themes_Default_Shared__Layout_cshtml.Execute() in D:\wtec.git\Singularity\Code\Singularity.Consumer\Themes\Themes\Default\Shared\_Layout.cshtml:line 33
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body)
   at System.Web.WebPages.WebPageBase.PopContext()
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
		
Powered by ELMAH, version 1.2.14706.955. Copyright (c) 2004, Atif Aziz. All rights reserved. Licensed under Apache License, Version 2.0.
</pre>

**Comment by Daniel15** [comment]
What version of JavaScriptEngineSwitcher is installed to your site? I wonder if there's a conflict with some newer version.

**Comment by sgraffite** [comment]
We're using JavaScriptEngineSwitcher version 1.5.0.  It looks like your projects are referencing version 1.2.4 but something is trying to call the EmbedHostObject method which was added in version 1.5.0 of JavaScriptEngineSwitcher.

It's possible updating React.NET and JSPool to reference the 1.50 version of JavaScriptEngineSwitcher will fix it.  I was having trouble getting the initial build to run from the batch file so I was unable to test that.

**Comment by Daniel15** [comment]
Ah, I think I know what's happening. `JSPool.JsEngineWithOwnThread` implements `IJsEngine`, and `EmbedHostObject` was added to that interface in JavaScriptEngineSwitcher 1.5. Since `JsEngineWithOwnThread` does not implement `EmbedHostObject`, it's failing. I'm guessing you have an assembly redirect in `Web.config`, otherwise you'd be seeing a more useful error message about a version mismatch.

**Comment by sgraffite** [comment]
Awesome, I really appreciate you looking into this.

**Comment by Daniel15** [comment]
Try upgrading to JSPool version 0.4.0 and let me know if you still see this issue :)

**Comment by sgraffite** [comment]
Initial testing looks good, I am no longer getting the error message.  I'll let you know if anything comes up :)
