### ISSUE TITLE
missing files - unable to compile

### ISSUE THREAD

**Issue by Strandedpirate** [reactjs/React.NET#262]
These files are missing and prevent a successful compile:

/src/SharedAssemblyVersionInfo.cs

/src/React.Core/Resources/babel.generated.min.js
/src/React.Core/Resources/react.generated.js
/src/React.Core/Resources/react.generated.min.js

**Comment by Daniel15** [comment]
See the readme. They're all generated files. Run dev-build.bat to generate them. You'll then be able to build in Visual Studio directly.

**Comment by Strandedpirate** [comment]
Tried the dev-build.bat previously but it bombed out. 

I had to change build.proj to separate these two projects like so:

		<Exec
			WorkingDirectory="$(MSBuildProjectDirectory)"
			Command="dnu restore --quiet --parallel src\React.AspNet"
		/>
		<Exec
			WorkingDirectory="$(MSBuildProjectDirectory)"
			Command="dnu restore --quiet --parallel src\React.Sample.Mvc6"
		/>

Error:
```

D:\Users\swifty\Documents\GitHub\React.NET>dev-build.bat
Microsoft (R) Build Engine version 14.0.25123.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/2/2016 1:59:34 AM.
Project "D:\Users\swifty\Documents\GitHub\React.NET\build.proj" on node 1 (default targets).
RestorePackages:
  tools\NuGet\nuget.exe restore src\React.sln
  All packages listed in packages.config are already installed.
  All packages listed in packages.config are already installed.
  dnu restore --quiet --parallel src\React.AspNet src\React.Sample.Mvc6
  Specify --help for a list of available options and commands.
  System.Exception: TODO: Error: unrecognized argument 'src\React.Sample.Mvc6'
     at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int3
  2 index, String argTypeName)
     at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
     at Microsoft.Framework.PackageManager.Program.Main(String[] args)
D:\Users\swifty\Documents\GitHub\React.NET\build.proj(46,3): error MSB3073: The command "dnu restore --quiet --parallel src\React.AspNet src\R
eact.Sample.Mvc6" exited with code 1.
Done Building Project "D:\Users\swifty\Documents\GitHub\React.NET\build.proj" (default targets) -- FAILED.


Build FAILED.

"D:\Users\swifty\Documents\GitHub\React.NET\build.proj" (default target) (1) ->
(RestorePackages target) ->
  D:\Users\swifty\Documents\GitHub\React.NET\build.proj(46,3): error MSB3073: The command "dnu restore --quiet --parallel src\React.AspNet src
\React.Sample.Mvc6" exited with code 1.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.41
Press any key to continue . . .
```

I continued to receive more errors related to NPM after fixing the above. So setting this aside for now.

**Comment by Daniel15** [comment]
Which version of ASP.NET 5 do you have installed? I've only tested with RC1 so the build may not work if you're using an unstable/nightly version.

What were the npm errors you saw?
