### ISSUE TITLE
.NET Core + Chakra + Debian can't find jsx file

### ISSUE THREAD

**Issue by malachib** [reactjs/React.NET#355]
I am trying to learn from the tutorial (https://reactjs.net/getting-started/tutorial.html)  and navigated my way around this issue #338 as it appears to apply to Debian also.  Now, it looks like it's almost working, but it appears the file path resolution is incorrect:

`System.IO.FileNotFoundException: Could not find file '/home/malachi/Projects/notos.server/src/notos.server/notos.server.web/bin/Debug/netcoreapp1.0/wwwroot/home/malachi/Projects/notos.server/src/notos.server/notos.server.web/bin/Debug/netcoreapp1.0/wwwroot/js/tutorial.jsx'.`

See how the path is doubling up? That doesn't seem quite right.  I doublechecked the path from `<script src="@Url.Content("~/js/tutorial.jsx")"></script>` and it spits out `<script src="/js/tutorial.jsx"></script>` , which seems to be expected behavior.

**Comment by Taritsyn** [comment]
Hello, Malachi!

> Unable to load DLL 'ChakraCore': The specified module could not be found.

You have installed the [JavaScriptEngineSwitcher.ChakraCore.Native.debian-x64](http://www.nuget.org/packages/JavaScriptEngineSwitcher.ChakraCore.Native.debian-x64/) package?

**Comment by malachib** [comment]
Yes, I have - to the best of my knowledge.  I have Startup.cs configured not only as described above, but also:

```
app.UseReact(config =>
            {
                // If you want to use server-side rendering of React components,
                // add all the necessary JavaScript files here. This includes
                // your components as well as all of their dependencies.
                // See http://reactjs.net/ for more information. Example:
                //config
                //  .AddScript("~/Scripts/First.jsx")
                //  .AddScript("~/Scripts/Second.jsx");

                // If you use an external build too (for example, Babel, Webpack,
                // Browserify or Gulp), you can improve performance by disabling
                // ReactJS.NET's version of Babel and loading the pre-transpiled
                // scripts. Example:
                //config
                //  .SetLoadBabel(false)
                //  .AddScriptWithoutTransform("~/Scripts/bundle.server.js");
            });

            app.UseStaticFiles();
```

Furthermore, my project.json has the following:

```
    "React.AspNet": "3.0.0",
    "JavaScriptEngineSwitcher.ChakraCore": "2.1.2",
    "JavaScriptEngineSwitcher.V8.Native.win-x64": "2.1.1",
    "JavaScriptEngineSwitcher.ChakraCore.Native.debian-x64": "2.1.0",
    "JavaScriptEngineSwitcher.ChakraCore.Native.osx-x64": "2.1.0",
    "JavaScriptEngineSwitcher.ChakraCore.Native.win-x64": "2.1.1",
    "JavaScriptEngineSwitcher.Extensions.MsDependencyInjection": "2.0.0",```
```

Lastly, the aforementioned exception is augmented also by this exception:

```
React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.JavaScriptEngineFactory ---> React.Exceptions.VroomJsInitialisationException: Failed to initialise VroomJs. This is most likely caused by the native library (libVroomJsNative.so) being out of date or your system lacking a compatible version of V8. Please run Mono with the `MONO_LOG_LEVEL=debug` environment variable for more debugging information, and refer to the ReactJS.NET Mono documentation at http://reactjs.net/guides/mono.html for further debugging hints.

 More details: Exception has been thrown by the target of an invocation.
   at React.JavaScriptEngineUtils.EnsureEngineFunctional[TEngine,TException](Func`2 exceptionFactory)
   at React.JavaScriptEngineFactory.GetFactory(JsEngineSwitcher jsEngineSwitcher, Boolean allowMsie)
   at React.JavaScriptEngineFactory..ctor(JsEngineSwitcher jsEngineSwitcher, IReactSiteConfiguration config, IFileSystem fileSystem)
   at lambda_method(Closure , Object[] )
   at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   --- End of inner exception stack trace ---
   at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.CustomObjectLifetimeFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.Resolve[ResolveType]()
   at React.AspNet.BabelFileMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

**Comment by Taritsyn** [comment]
What version of Ubuntu are you using? 

Give a example of the `frameworks` section from the `project.json` file.

**Comment by malachib** [comment]
It's Ubuntu 16.04.01 & uname produces:

`Linux vm-c131-ubuntudev 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

frameworks section looks like:

```
  "frameworks": {
    "netcoreapp1.0": {
      "buildOptions": {
        "define": [ "DNXCORE50" ]
      }
    }
  },
```

My debian machine uname produces: `Linux vm-c131-debian 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux`

**Comment by Taritsyn** [comment]
```json
"frameworks": {
  "netcoreapp1.0": {
    "buildOptions": {
      "define": [ "DNXCORE50" ]
    }
  }
},
```

I recommend to remove all the JavaScriptEngineSwitcher.V8 packages, because it is not compatible with the `netcoreapp1.0`.

> My debian machine uname produces: `Linux vm-c131-debian 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux`

I have built and tested the `libChakraCore.so` assembly for the [JavaScriptEngineSwitcher.ChakraCore.Native.debian-x64](http://www.nuget.org/packages/JavaScriptEngineSwitcher.ChakraCore.Native.debian-x64/) on Ubuntu 16.04.1 x64.
Much has been done by analogy with the [ASP.NET Libuv Package](https://github.com/aspnet/libuv-package), therefore not tested for compatibility with Debian.

Try to build the `libChakraCore.so` assembly on Debian. To do this, follow these steps:

 1. Download source code of [ChakraCore version of October 29, 2016](https://github.com/Microsoft/ChakraCore/tree/b9a74eaeab408bdceb3431db0adb570c92f14e0a) and uncompress it.
 2. Open terminal and start the update process:
 ```
 sudo apt-get update
 sudo apt-get dist-upgrade
 ```
 3. Install dependencies:
 ```
 sudo apt-get install -y build-essential cmake clang libunwind-dev libicu-dev
 ```
 4. Change current directory to the directory with source code of ChakraCore.
 5. Start build:
 ```
 ./build.sh
 ```
 6. From the `BuildLinux/Release/` directory copy the `libChakraCore.so` file to the `~/.nuget/packages/JavaScriptEngineSwitcher.ChakraCore.Native.debian-x64/2.1.0/runtimes/debian-x64/native/` directory.

After all these steps, run your web application.

**Comment by malachib** [comment]
Thank you for this insight.

Firstly, I'll ensure the .V8 is removed.

Secondly, struggling a bit since Debian and its ever-so-antiquated packages are only up to clang 3.5 but ChakraCore wants 3.7.  Still futzing with that.  

Lastly, revisiting the Ubuntu scenario (the title issue) - any clues as to why the FileNotFoundException is occurring?

**Comment by Daniel15** [comment]
> struggling a bit since Debian and its ever-so-antiquated packages

This is why I use Debian Testing (Stretch) in production, it's still stable enough for everyday use :)

> Lastly, revisiting the Ubuntu scenario (the title issue) - any clues as to why the FileNotFoundException is occurring?

I suspect something is wrong with MapPath, like @Taritsyn mentioned. It's working fine for me on Mono (http://dan.cx/socialfeed.htm is running on Mono) but I haven't done extensive testing on .NET Core on Linux. Pull requests are appreciated :)

**Comment by malachib** [comment]
OK well I appreciate the attention and feedback - for now I am gonna do some workarounds,  Since I'm so new to react, I'm not even sure how extensively I'll be using it.  When things settle down and if I'm still in the react world, I'll have a look at AspNetFileSystem

**Comment by pablinos** [comment]
I had this same error running the dotnet docker container. I went to get the source to build a version of ChakraCore as suggested and noticed that there was a linux-x64 binary version. 

https://github.com/Microsoft/ChakraCore/releases

I downloaded that and copied the `libCharkaCore.so` to the `~/.nuget/packages/JavaScriptEngineSwitcher.ChakraCore.Native.debian-x64/2.1.0/runtimes/debian-x64/native/` directory and it fixed it. 

Would it be worth updating the native packages so it's just a linux-x64 one and could track the official binary releases?

**Comment by Taritsyn** [comment]
Hello, Paul!

> I had this same error running the dotnet docker container. 

Which Linux are you using?

> I downloaded that and copied the libCharkaCore.so to the ~/.nuget/packages/JavaScriptEngineSwitcher.ChakraCore.Native.debian-x64/2.1.0/runtimes/debian-x64/native/ directory and it fixed it.

May be need to upgrade to version 2.4.6?

> Would it be worth updating the native packages so it's just a linux-x64 one and could track the official binary releases?

I do not quite understand how Microsoft's employees build such an assembly. In [official instruction](https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore#linux), nothing is written about this. Microsoft's version of the `libCharkaCore.so` assembly weighs 2.5 times more than my version. As an experiment, I will add the JavaScriptEngineSwitcher.ChakraCore.Native.linux-x64 package to version 3.0.0 Alpha 6.

**Comment by pablinos** [comment]
Hi,

Linux version is Debian Jessie as it's the dotnet Docker image.

That is weird that it defaulted to the 2.1 version. Could it be to do with the project being dotnet core/tools  1.1.4?

I'm not sure how they'd be a universal library like that either, but being 2.5 times the size, it does suggest there's a lot more in there! Perhaps they explain it if we asked the question there?

**Comment by Taritsyn** [comment]
> I'm not sure how they'd be a universal library like that either, but being 2.5 times the size, it does suggest there's a lot more in there! Perhaps they explain it if we asked the question there?

It seems, that Microsoft's employees build a ChakraCore library with the following parameters:

```
./build.sh --embed-icu -j=2
```

I.e. your problem is very similar to the [same problem with OS X](https://github.com/Taritsyn/JavaScriptEngineSwitcher/issues/28). Both problems caused by lack of a suitable version of the ICU library. All this universality is achieved through embedding of the ICU-57 library to the ChakraCore assembly (because of this, assembly size is increased by 2,5 times).

**Comment by pablinos** [comment]
Ah, unicode and timezones, two things that have given me a lot of headaches over the years!

I'll try installing ICU and see if the library version in the Debian package works or not.

**Comment by Taritsyn** [comment]
@pablinos In [version 3.0.0 Alpha 6](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v3.0.0-alpha.6) ICU-57 library was embedded into the `libChakraCore.so` and `libChakraCore.dylib` assemblies.

**Comment by Taritsyn** [comment]
@pablinos I moved the corresponding functionality from 3.X branch to [version 2.4.12](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v2.4.12).

**Comment by pablinos** [comment]
Brilliant, thanks for that, I'll take a look!


--
Paul Bunkham
07881586923
paul@dobit.co.uk
www.dobit.co.uk

Dobit Ltd is a company registered in England and Wales with company number
7035336
Registered Address: 67 Church Road, Hove, East Sussex BN3 2BD
