### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by andreymir** [reactjs/React.NET#398]
Not sure whether it is a React.NET or ClearScript issue. I'm trying to run my application in a docker container. At strartup it crashes with the System.AccessViolationException exception.

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at V8Context.Create(SharedPtr<V8Isolate>* , StdString* , Boolean , Boolean , Int32 )
   at Microsoft.ClearScript.V8.V8ContextProxyImpl..ctor(V8IsolateProxy gcIsolateProxy, String gcName, Boolean enableDebugging, Boolean disableGlobalMembers, Int32 debugPort)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Microsoft.ClearScript.V8.V8Proxy.CreateImpl[T](Object[] args)
   at Microsoft.ClearScript.V8.V8ScriptEngine..ctor(V8Runtime runtime, String name, V8RuntimeConstraints constraints, V8ScriptEngineFlags flags, Int32 debugPort)
   at JavaScriptEngineSwitcher.V8.V8JsEngine..ctor(V8Settings settings)
   at JavaScriptEngineSwitcher.V8.V8JsEngineFactory.CreateEngine()
   at React.JavaScriptEngineFactory.GetFactory(JsEngineSwitcher jsEngineSwitcher, Boolean allowMsie)
   at React.JavaScriptEngineFactory..ctor(JsEngineSwitcher jsEngineSwitcher, IReactSiteConfiguration config, IFileSystem fileSystem)
   at lambda_method(Closure , Object[] )
   at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.CustomObjectLifetimeFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at React.TinyIoC.TinyIoCContainer.Resolve[ResolveType]()
   at React.AspNet.HtmlHelperExtensions.get_Environment()
   at React.AspNet.HtmlHelperExtensions.React[T](IHtmlHelper htmlHelper, String componentName, T props, String htmlTag, String containerId, Boolean clientOnly, Boolean serverOnly, String containerClass)
   at AspNetCore._Views_Site_Menu_cshtml.<ExecuteAsync>d__33.MoveNext() in /Views/Site/Menu.cshtml:line 3
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at AspNetCore._Views_Site_Menu_cshtml.ExecuteAsync()
```

Without container it is runs fine.

**Comment by andreymir** [comment]
Posted the issue to ClearScript https://clearscript.codeplex.com/workitem/120

**Comment by Taritsyn** [comment]
Hello, Andrey!

What versions of the [JavaScriptEngineSwitcher.V8](http://www.nuget.org/packages/JavaScriptEngineSwitcher.V8/), [JavaScriptEngineSwitcher.V8.Native.win-x86](http://www.nuget.org/packages/JavaScriptEngineSwitcher.V8.Native.win-x86/) and [JavaScriptEngineSwitcher.V8.Native.win-x64](http://www.nuget.org/packages/JavaScriptEngineSwitcher.V8.Native.win-x64/) packages do you use?

**Comment by andreymir** [comment]
Hi Andrey! 
Thanks for your help! Initially I tries with older version but it has the same issue. Now I'm using the latest version available 2.2.0.
![image](https://cloud.githubusercontent.com/assets/226866/25106166/de1ea9ae-23d0-11e7-93f8-0c7bec08722f.png)

**Comment by Taritsyn** [comment]
> Now I'm using the latest version available 2.2.0.

This error no longer occurs?

**Comment by andreymir** [comment]
No, still have the same exception.
However, there is a theory it could be a memory limit issue. Someone suggested that V8 could crash if it could not allocate enough memory

> Another possibility is that the V8 runtime is too constrained to complete startup. Are you using V8RuntimeConstraints to specify memory usage limits?
> Also, could it be that Docker is imposing various limits on your application?
https://clearscript.codeplex.com/workitem/120

I'm going to check today if there are options in docker related to memory and will see if it fixes the issue.

**Comment by Taritsyn** [comment]
Try to [register the `V8JsEngine` manually](https://github.com/Taritsyn/JavaScriptEngineSwitcher/issues/27#issuecomment-292753537).

> Are you using V8RuntimeConstraints to specify memory usage limits?

I recommend you also read the [“Registration of JS engines”](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/Registration-of-JS-engines) and [“JS Engine Switcher: V8”](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/JS-Engine-Switcher:-V8) sections of the JavaScript Engine Switcher's documentation.

If you plan to use ASP.NET Core in your projects, then try the [JavaScriptEngineSwitcher.ChakraCore.](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/JS-Engine-Switcher:-ChakraCore)

**Comment by andreymir** [comment]
I think we could close the issue. I did some testing today and it seems that it was a memory limit issue.
