### ISSUE TITLE
Incorrect paths for ScriptsWithoutTransform aren't reported the way Scripts are

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [reactjs/React.NET#469]
Suppose you have a single JS file you'd like in your `ReactConfig` `Scripts` (on the AspNet variant) and you pass the wrong path to it:

```csharp
ReactSiteConfiguration.Configuration
    .SetLoadBabel(false)
    .AddScript("Views/Home/HelloWorld.jsx");
```

This will correctly get reported as missing when React.NET tries to pass it to Babel:

```csharp
Could not find a part of the path 'C:\path\to\deployment\Views\Home\HelloWorld.jsx'.
Source: mscorlib
Call Stack:
 at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
 at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
 at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
 at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
 at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
 at React.Babel.TransformFileWithSourceMap(String filename, Boolean forceGenerateSourceMap)
 at React.Babel.TransformFile(String filename)
 at React.ReactEnvironment.EnsureUserScriptsLoaded()
 at React.ReactEnvironment.CreateComponent[T](String componentName, T props, String containerId, Boolean clientOnly)
 at React.Web.Mvc.HtmlHelperExtensions.React[T](HtmlHelper htmlHelper, String componentName, T props, String htmlTag, String containerId, Boolean clientOnly, Boolean serverOnly, String containerClass)
 at ASP._Page_Views_Home_ElectricBoogaloo_cshtml.Execute() in c:\path\to\deployment\Views\Home\ElectricBoogaloo.cshtml:line 24
 at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
 at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
 at System.Web.WebPages.StartPage.ExecutePageHierarchy()
 at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
 at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
 at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
 at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
 at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
 at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
 at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
```

However, if you switch it to a non-transformed script, it silently fails and just complains that there's no component of that name. 

The problem here is that nothing verifies the script exists when it's added. I suspect there's a `JavaScriptEngineFactory` `_scriptLoadException` somewhere in a background thread that's not being thrown.

Potential solution: verify scripts exist when they're added (unless a `SkipScriptVerification` flag is passed)?

**Comment by dustinsoftware** [comment]
We've added better support for re-throwing JS engine exceptions in the latest 4.0.0 rc.
