### ISSUE TITLE
React.Router has a flaky test

### ISSUE THREAD

**Issue by Daniel15** [reactjs/React.NET#472]
The build seems to randomly fail on `React.Tests.Router.HtmlHelperExtensionsTest.ShouldRunCustomContextHandler`:
```
[xUnit.net 00:00:00.2936128]   Discovering: React.Tests
  [xUnit.net 00:00:00.7217786]   Discovered:  React.Tests
  [xUnit.net 00:00:00.9747520]   Starting:    React.Tests
  [xUnit.net 00:00:02.4140782]     React.Tests.Router.HtmlHelperExtensionsTest.ShouldRunCustomContextHandler [FAIL]
  [xUnit.net 00:00:02.4150445]       System.NullReferenceException : Object reference not set to an instance of an object.
  [xUnit.net 00:00:02.4157439]       Stack Trace:
  [xUnit.net 00:00:02.4172806]            at React.Router.HtmlHelperExtensions.ReactRouterWithContext[T](HtmlHelper htmlHelper, String componentName, T props, String path, String htmlTag, String containerId, Boolean clientOnly, Boolean serverOnly, String containerClass, Action`2 contextHandler)
  [xUnit.net 00:00:02.4174844]         Router\HtmlHelperExtensionsTest.cs(204,0): at React.Tests.Router.HtmlHelperExtensionsTest.ShouldRunCustomContextHandler()
  [xUnit.net 00:00:02.4358859]   Finished:    React.Tests
  Failed   React.Tests.Router.HtmlHelperExtensionsTest.ShouldRunCustomContextHandler
EXEC : error Message:  [C:\projects\react-net\build.proj]
   System.NullReferenceException : Object reference not set to an instance of an object.
  Test Run Failed.
  Stack Trace:
     at React.Router.HtmlHelperExtensions.ReactRouterWithContext[T](HtmlHelper htmlHelper, String componentName, T props, String path, String htmlTag, String containerId, Boolean clientOnly, Boolean serverOnly, String containerClass, Action`2 contextHandler)
     at React.Tests.Router.HtmlHelperExtensionsTest.ShouldRunCustomContextHandler()
```

cc @gunnim

**Comment by gunnim** [comment]
https://github.com/reactjs/React.NET/pull/475 seems to take care of the issue, i'm no longer able to reproduce the bug 👍

**Comment by Daniel15** [comment]
Thank you for fixing it, @dustinsoftware :D
