### ISSUE TITLE
Uncaught FileNotFoundException kills the process

### ISSUE THREAD

**Issue by LachlanStuart** [reactjs/React.NET#502]
When I'm recompiling React components, ReactJS.NET seems to try to access the files while they're gone, causing a FileNotFoundException to be thrown. As that FileNotFoundException is uncaught, it causes the process to die. The thread that this happens in is controlled by ReactJS.NET, so it's not fixable in user code. 

This is the exception:

```
{System.IO.FileNotFoundException: Could not find file '...\dist\server.js'.
File name: '...\dist\server.js'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at React.JavaScriptEngineFactory.LoadUserScripts(IJsEngine engine)
   at React.JavaScriptEngineFactory.InitialiseEngine(IJsEngine engine)
   at JSPool.JsPool`2.CreateEngine()
   at JSPool.JsPool`2.PopulateEngines()
   at JSPool.FileWatcher.OnTimer(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()}
```

**Comment by dustinsoftware** [comment]
Thanks for the report. It would be good to retry automatically a few times when this happens.

**Comment by dustinsoftware** [comment]
This issue is pretty old and we've done a little work in this space, can you update to the latest rc to see if it is fixed?
