### ISSUE TITLE
"ReactJS.NET has not been initialised correctly. Please ensure you have called services.AddReact() and app.UseReact() in your Startup.cs file.

### ISSUE THREAD

**Issue by mche1987** [reactjs/React.NET#546]
On .Net 4.5.2 MVC5, on ReactJs 3.3. 

Recently upgraded React versions from 15.4.1 to 16.4.0 and I'm getting this error when accessing a page that has and MVC page react component. 

` "ReactJS.NET has not been initialised correctly. Please ensure you have called services.AddReact() and app.UseReact() in your Startup.cs file." `

Inner exceptions:
`TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment`
`TinyIoCResolutionException: Unable to resolve type: React.JavaScriptEngineFactory`
`ReactNotInitialisedException: React has not been loaded correctly. Please expose your version of React as global variables named 'React', 'ReactDOM' and 'ReactDOMServer', or enable the 'LoadReact' configuration option to use the built-in version of React.`

As I am using .NET 4.5x and not Core, not sure why I'm getting that top level Exception message.

That said, this is only happening when we update out React and ReactDOM from 15.x to 16.x. Is there something I need to do as far as exposing `React`, `ReactDOM` and `ReactDOMServer` globally? If so, is there documentation on how to do this?

**Comment by mche1987** [comment]
Yes, using webpack. The React Configuration portion looks like below:

```
ReactSiteConfiguration.Configuration
    .SetLoadReact(false)
    .SetLoadBabel(false)
    .AddScriptWithoutTransform("~/xxx.js")
```

I've tried flipping the `.SetLoadingReact` to `true` and accessing a React-loaded page but there ends up being a breakage at the first `@Html.React("componentName", new{...})` helper with the error stating:

```
Error while rendering "componentName" to "react_gaukTLRKH0SHeZcoqd2EaQ": ReferenceError: 'setTimeout' is not defined
  at tryRender (Script Document [14]:1604:9)
  at d (React.Core.Resources.react.generated.min.js:1:7423)
  at e.prototype.render (React.Core.Resources.react.generated.min.js:1:13258)
  at e.prototype.read (React.Core.Resources.react.generated.min.js:1:13169)
  at W.renderToString (React.Core.Resources.react.generated.min.js:1:16129)
  at Global code (Script Document [17]:1:1)
Line: 1604
Column:9
```

In my bundled component script file, I find the spot referencing `setTimeout`, when I comment it out, the page loads but not with my components. I get several errors thrown by my missing `static propTypes` but I assume that's because the SSR didn't load them to the page to be referenced. (FWIW, in the `@Html.React` helper when I set it the `clientOnly:` to equal `true`, it doesn't break at the `setTimeout` but the same errors regarding the missing `static propTypes` is thrown.
