### ISSUE TITLE
ReactJS.NET is throwing errors on NetCore2 app

### ISSUE THREAD

**Issue by Taerarenai** [reactjs/React.NET#624]
I've been trying for the past days to add ReactJS.NET to my existing NetCore2 app with a LOT of errors.

First i've tried the tutorial, got lots of errors such as "ReactJS.NET is not initialized properly...." even tho' i followed the steps by the book.
After a few searches i've looked at the MVCCore sample and modified my code accordingly, but now i am getting a different error.

`npm run webpack` runs without any errors. While im trying to load the page with react, the react apps dont load throwing an error such as  `React.Exceptions.ReactServerRenderingException: Error while rendering "RootComponent" to "react_0HLI7BKUVRVS1": Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

This is my webpack.config.js ->

```
const path = require('path');

module.exports = {
    // This is our entry point containing the code 
    // required to perform server-side rendering.
    entry: './React/main.js',
    output: {
        path: path.resolve(__dirname, 'wwwroot/dist'),
        filename: 'bundle.js'
    },
    module: {
        // Transform .jsx files.
        rules: [
            {
                loader: 'file-loader?name=[name].[ext]',
                test: /\.jsx$/,
                //use: 'jsx-loader?harmony',
                exclude: /node_modules/,
                loader: 'babel-loader',
                query: {
                    "presets": [
                        "@babel/preset-react",
                        "@babel/preset-env"
                    ],
                    "plugins": [
                        "@babel/plugin-proposal-class-properties"
                    ]
                },
            }
        ]
    },
    resolve: {
        // Ensure we can deal with .js and .jsx and require files.
        extensions: ['.js', '.jsx']
    },
    // Set mode for development, production or none.
    mode: 'none'
};
```

This is my main.js -> 

```
require('expose-loader?React!react');
require('expose-loader?ReactDOM!react-dom');
require('expose-loader?ReactDOMServer!react-dom/server');

require('expose-loader?RootComponent!./App.jsx');
```

This is my App.jsx -> 

```
import { Component, Fragment } from 'react';

export default class App extends Component {
    render() {
        return (
            <Fragment>
                <div className="appStart">Test React fwafasfaw</div>
            </Fragment>
        );
    }
}
```

And finally this is my view -> 

```
@{
    ViewData["Title"] = "ReactTest";
}
<script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin="true"></script>
<script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin="true"></script>


@Html.React("RootComponent", new { initialComments = Model.SPOResponse })
<script src="~/dist/bundle.js"></script>
@Html.ReactInitJavaScript()

<h2>ReactTest</h2>
<div id="content"></div>
```

Any tips ? My full question was already asked on StackOverflow, but no answer yet... 
( https://stackoverflow.com/questions/53231394/unable-to-add-reactjs-net-on-netcore-2)

Hopefully you can help me out, thanks.

**Comment by dustinsoftware** [comment]
Hi there, can you look at the sample code we have in this repo for webpack?
It should be up to date with .net Core.

**Comment by Taerarenai** [comment]
If you mean this one ( https://github.com/reactjs/React.NET/tree/master/src/React.Sample.Webpack.CoreMvc) i've already looked at it as i said in my posted issue. It helped solve some of the problems, but the rendering problem came up and by comparing the code i can't see any major differences (except file names and paths).

**Comment by dustinsoftware** [comment]
Is your component being rendered properly? Try to copy over the example
component from the sample to your app, including the webpack config. That
will rule out a problem in the library.

**Comment by dustinsoftware** [comment]
Oh. Try using module.exports instead of export default in your root
component.

**Comment by Taerarenai** [comment]
By using module.exports i assume you mean that i change my code from `require('expose-loader.....)` to use module.exports right? (still learning here).

I changed it to this -> 
```
module.exports = {
    RootComponent: require('./App'),
    React: require('react'),
    ReactDOM: require('react-dom'),
    ReactDOMServer: require('react-dom/server')
};
```
And now i'm getting `React.Exceptions.ReactNotInitialisedException: ReactJS.NET has not been initialised correctly. Please ensure you have called services.AddReact() and app.UseReact() in your Startup.cs file. ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.ReactEnvironment ---> React.TinyIoC.TinyIoCResolutionException: Unable to resolve type: React.JavaScriptEngineFactory ---> React.Exceptions.ReactNotInitialisedException: React has not been loaded correctly: missing (React, ReactDOM, ReactDOMServer).Please expose your version of React as global variables named 'React', 'ReactDOM', and 'ReactDOMServer', or enable the 'LoadReact'configuration option to use the built-in version of React.
`
services.AddReact() and app.UseReact() is already added.

**Comment by dustinsoftware** [comment]
No sorry. I mean add this statement to the bottom of your root component.

module.exports = RootComponent;

There is a known issue mixing expose loader with “export default” syntax.

**Comment by Taerarenai** [comment]
I think it was because i was using the newest version of babel (@babel/core). I switched to the package.json from the example and i managed to get it working after installing a few more packages (such as babel-stage-2).

I have one more question tho', after building my page even tho' everything seems to load fine (at least visually), i see this error in the browsers console ->

```
Call stack: Error
   at MockConsole.prototype._handleCall (React.Core.Resources.shims.js:27:3)
   at Anonymous function (bundle.js:39300:1)
   at __webpack_require__ (bundle.js:20:12)
   at Anonymous function (bundle.js:39249:47)
   at Anonymous function (bundle.js:39249:29)
   at __webpack_require__ (bundle.js:20:12)
   at Anonymous function (bundle.js:12701:1)
   at __webpack_require__ (bundle.js:20:12)
   at Anonymous function (bundle.js:63:11)
   at Global code (bundle.js:1:11)
```

Any idea what couldve caused it? 

Thanks for taking the time to answer me, appreciate it ^^.

**Comment by Taerarenai** [comment]
@dustinsoftware Did a bit of debugging on the client side and it seems like the console error comes from a "weird" place.

`"_Component is not defined"`

Any tip on why this happens? Functionality doesnt seem to be affected (unless this is the reason for which my app seems to load slower than a client side render & it lods first 2 text fields and then the Fabric UI List that i have with items from the backend).
