### ISSUE TITLE
Does not import MVC4

### ISSUE THREAD

**Issue by sremiger1** [reactjs/React.NET#716]
I get the following error once I attempt to create and spread out the components to sub-components.  

1. Everything worked in a single file called BlockStart.jsx, being called from the BlockWizard.cshtml file.
2. Created a second component called BlockBasic.jsx which is going to be a sub component to BlockStart.jsx.
3. Running everything I get the error below.
4. From what I understand in the ReactConfig.cs, I should not have to reference BlockBasic.jsx because BlockStart.jsx has an import.
5. Using the V8JsEngine if that matters.

**Question(s)**
Can I have sub-components , I would think I can because your examples show them but I cannot get the examples for MVC4 to run.

**BlockBasic.jsx**
```
export class BlockBasic extends React.Component {
    static propTypes = { block: PropTypes.block };

    render() {
        return (
            <div className="panel panel-primary">
                <div className="panel-heading">Basic Information</div>
                <div className="panel-body">
                    Hello in Panel <br />
                    {this.props.block.TenantBlockName}
                </div>
            </div>
        );
    }
}
```
**BlockStart.jsx**
```
import { BlockBasic } from './BlockBasic.jsx';

class BlockStart extends React.Component {
    static propTypes = { block : PropTypes.block };
    render() {
        return (
            <div className="container-fluid"><BlockBasic block={this.props} />
                {this.props.TenantBlockName}
            </div >
       );
    }
}
```
**BlockWizard.cshtml**
```
@model ApplicantCenter3.Admin.Models.TenantBlockViewModel
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Block Wizard</title>
</head>
<body>
    <div id="content"></div>
    <script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/react/16.4.0/umd/react.development.js"></script>
    <script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.4.0/umd/react-dom.development.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/remarkable/1.7.1/remarkable.min.js"></script>
    @Html.React("BlockStart", Model)
    @Html.ReactInitJavaScript()
</body>
</html>
```
**Error Message at runtime**
```
React.Exceptions.ReactScriptLoadException
  HResult=0x80131500
  Message=Error while loading "~/Scripts/Block/Wizard/BlockBasic.jsx": SyntaxError: Unexpected token export
   at BlockBasic.jsx:199:1 -> export default BlockBasic;
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

Inner Exception 1:
JsCompilationException: SyntaxError: Unexpected token export
   at BlockBasic.jsx:199:1 -> export default BlockBasic;

Inner Exception 2:
ScriptEngineException: SyntaxError: Unexpected token export
```

**Comment by dustinsoftware** [comment]
ES6 modules are not yet natively supported without webpack, you tried using that yet?

**Comment by dustinsoftware** [comment]
Since it doesn't look like this is a bug, I'm closing this issue. Please feel free to comment if you'd like some more help 👍
