### ISSUE TITLE
React.Exceptions.ReactScriptLoadException: ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by kdelmonte** [reactjs/React.NET#725]
Thanks for filing a bug! To save time, if you're having trouble using the library, please check off the items you have tried. If you are just asking a question, skip right to the bottom.

### Please verify these steps before filing an issue, and check them off as you go
- [x] The relevant native JavascriptEngineSwitcher library packages are installed (such as `JavaScriptEngineSwitcher.V8.Native.win-x64`)
- [x] The VC++ 2017 runtime is installed
- [x] The value of `SetUseReact` and `SetUseBabel` is correct in `ReactConfig.cs` or `Startup.cs`
- [x] I've looked at the sample projects in this repo to verify that my app is configured correctly

### I'm using these library versions:
- `ReactJS.NET`: 4.0.0
- `JavaScriptEngineSwitcher`: 3.0.5
- `react` and `react-dom`: 16.7.0
- `webpack`: 4.29.0
- `node`: 10.11.0

### Runtime environment:
- OS: Windows 10 64-bit
- .NET Framework or .NET Core Version: .NET Framework4.5

### Steps to reproduce

-------

I am getting a `React.Exceptions.ReactScriptLoadException` when trying to load my webpack bundle:

Message: 
```
ReferenceError: exports is not defined
   at server.en.main.js:1:1 -> exports["server"] =
```
StackTrace:
```
   at JavaScriptEngineSwitcher.V8.V8JsEngine.InnerExecute(IPrecompiledScript precompiledScript)
   at JavaScriptEngineSwitcher.Core.JsEngineBase.Execute(IPrecompiledScript precompiledScript)
   at React.JavaScriptEnginePrecompilationUtils.TryExecuteFileWithPrecompilation(IJsEngine engine, ICache cache, IFileSystem fileSystem, String path, Func`2 scriptLoader)
   at React.JavaScriptEngineFactory.LoadUserScripts(IJsEngine engine)
```

Inner Exception:

Message:
```
ReferenceError: exports is not defined
```

StackTrace:
```
   at V8Exception.ThrowScriptEngineException(V8Exception* )
   at Microsoft.ClearScript.V8.V8ContextProxyImpl.Execute(V8Script gcScript, Boolean evaluate)
   at Microsoft.ClearScript.V8.V8ScriptEngine.<>c__DisplayClass54_0.<Execute>b__0()
   at Microsoft.ClearScript.ScriptEngine.ScriptInvokeInternal[T](Func`1 func)
   at Microsoft.ClearScript.V8.V8ScriptEngine.<>c__DisplayClass76_1`1.<ScriptInvoke>b__0()
   at Microsoft.ClearScript.V8.?A0x8cbc81c2.LockCallback(Void* pvArg)
   at Microsoft.ClearScript.V8.V8ContextProxyImpl.InvokeWithLock(Action gcAction)
   at Microsoft.ClearScript.V8.V8ScriptEngine.ScriptInvoke[T](Func`1 func)
   at Microsoft.ClearScript.V8.V8ScriptEngine.Execute(V8Script script, Boolean evaluate)
   at JavaScriptEngineSwitcher.V8.V8JsEngine.InnerExecute(IPrecompiledScript precompiledScript)
```

**Comment by dustinsoftware** [comment]
That's a new one. It looks like webpack is not emitting a correct bundle for you. Are you using code splitting at all? Could you upload the webpack config to a gist?

It could be related to this issue: https://github.com/webpack/webpack/issues/3974#issuecomment-369260590

To verify that this error also occurs on the client, please try calling `@Html.React(..., clientOnly:true);`, which will skip server rendering.

You can also try loading the server bundle directly in node by calling `node --require server.bundle.js`

**Comment by kdelmonte** [comment]
While the doing this research for you, I noticed that the the config (which is massive and spread across separate files) had a `target` of `node`. I'm thinking that must e the issue.

Thanks for the help!

Config excerpt: 
```
module.exports = [{
  name: 'server.en',
  entry: ['redacted'],
  target: 'node',
  output: {
    path: 'redacted',
    publicPath: 'redacted',
    filename: 'server.en.[name].js',
    pathinfo: false,
    chunkFilename: 'server.en.[name].js',
    library: 'server',
    libraryTarget: 'commonjs'
  },
  module: {
    strictExportPresence: true,
    rules: [{
      test: /\.jsx?$/,
      exclude: /node_modules/,
      use: {
        loader: 'babel-loader',
        options: {
          cacheDirectory: true,
          babelrc: true,
        }
      }
    }]
  }
}];

```
